/*
 * generated by Xtext 2.10.0
 */
package org.xtext.example.issue60


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Issue60StandaloneSetup extends Issue60StandaloneSetupGenerated {

	def static void doSetup() {
		new Issue60StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
